name: Feature Request
description: Suggest a feature, plugin, or mechanic for the server.
body:
- type: markdown
  attributes:
      value: "Please start your title with one of the following: [Feature], [Plugin], [Mechanic]."
- type: dropdown
  attributes:
    label: Server
    description: "Which server the feature request is on."
    options:
      - Nova
      - Aurora
      - Hub
  validations:
    required: true
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe.
    description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: "A clear and concise description of what you want to happen."
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: "Add any other context or screenshots about the feature request here."
  validations:
    required: false
